artifact_location: file:///home/mle-user/mle_projects/mle-mlflow/notebooks/mlflow_experiments_store/0
creation_time: 1735130199122
experiment_id: '0'
last_update_time: 1735130199122
lifecycle_stage: active
name: Default
