artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/9b2af5abb615416a959aded2af490db2/artifacts
end_time: 1735131296591
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9b2af5abb615416a959aded2af490db2
run_name: Default
run_uuid: 9b2af5abb615416a959aded2af490db2
source_name: ''
source_type: 4
source_version: ''
start_time: 1735131296583
status: 3
tags: []
user_id: mle-user
